config/routes.rb
Rails.application.routes.draw do

   # 顧客側のdeviseルーティング設定
  devise_for :customers, controllers: {

    registrations: "customer/registrations",
    sessions: "customer/sessions"
  }


  root 'homes#top'

  # 管理者側のdeviseルーティング設定
  devise_for :admins, controllers: {
    sessions: "admin/sessions"
  }

  get 'about' => 'homes#about', as: 'about'


  #会員側のルーティング設定
  resources :addresses, except: [:show, :new]

  # resources の下にいると？うまく遷移しなかったので上にあげてみました。
  post 'orders/confirm' => 'orders#confirm', as: 'confirm'
  get 'orders/complete' => 'orders#complete', as: 'complete'
  resources :orders, except: [:edit, :update, :destroy]

  delete 'cart_items/alldestroy' => 'cart_items#all_destroy', as: 'all_destroy'
  resources :cart_items, except: [:show, :new, :edit]

  get 'items/search' => 'items#search', as: 'search'
  resources :items, only: [:index, :show]

  # 管理者側のルーティング設定
  namespace :admin do
    resources :order_details, only: :update
    resources :orders, only: [:index, :show, :update]
    resources :categories, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :items, except: :destroy
  end

  scope module: :customer do
    get 'customers/unsubscribe' => 'customers#unsubscribe', as: 'unsubscribe'
    patch 'customers/out' => 'customers#out', as: 'out'
    resources :customers, only: [:show, :edit, :update]
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum is_deleted: { enable: false, disable: true }

  validates :last_name,  presence: true
  validates :first_name, presence: true
  # カタカナ制限
  validates :last_name_kana,  presence: true, format: {with: /\A[\p{katakana}\p{blank}ー－]+\z/, message: 'はカタカナで入力して下さい。'}
  validates :first_name_kana, presence: true, format: {with: /\A[\p{katakana}\p{blank}ー－]+\z/, message: 'はカタカナで入力して下さい。'}
  # 電話番号はハイフンなしの10桁もしくは11桁のみ登録可能とする
  validates :phone_number, presence: true, format: {with: /\A\d{10}$|^\d{11}\z/, message: '10桁か11桁の電話番号を入力してください。'}
  # 郵便番号はハイフンなしの7桁のみ登録可能とする
  validates :postcode,  presence: true, format: { with: /\A\d{7}\z/ }
  validates :address, presence: true

  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy


  def user_address
        '〒'+postcode+' '+address+' '+first_name+last_name
  end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    # kaminariを使用するための記述
    @customers = Customer.page(params[:page]).per(10)
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to admin_customer_path(@customer.id)
    else
      edit_admin_customer_path(@customer.id)
    end
  end

  private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postcode, :address, :phone_number, :email, :is_deleted)
  end
  
end

app/controllers/customer/addresses_controller.rb
class Customer::AddressesController < ApplicationController
  def index
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/customer/cart_items_controller.rb
class Customer::CartItemsController < ApplicationController
  def index
  end

  def create
  end

  def update
  end

  def destroy
  end

  def all_destroy
  end
end

app/controllers/customer/confirmations_controller.rb
# frozen_string_literal: true

class Customer::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customer/customers_controller.rb
class Customer::CustomersController < ApplicationController
  before_action :authenticate_customer!
  before_action :ensure_correct_customer, {only: [:show, :edit]}

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
       redirect_to customer_path(@customer)
    else
       render 'edit'
    end
  end

  def unsubscribe
    @customer = current_customer
  end

  def out
    @customer = current_customer
    if @customer.update(is_deleted: true)
       #URLを踏ませずにコントローラーから直接サインアウトの指示を出す
       sign_out current_customer
    end
       redirect_to root_path
  end

  private

  def customer_params
    params.require(:customer).permit(:is_deleted, :last_name, :first_name, :last_name_kana, :first_name_kana,:phone_number, :email, :password, :postcode, :address)
  end

  def ensure_correct_customer
    @customer = Customer.find(params[:id])
    if current_customer.id != @customer.id
      redirect_to root_path
    end
  end

end

app/controllers/customer/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customer::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customer/orders_controller.rb
class Customer::OrdersController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def confirm
  end

  def create
  end

  def complete
  end
end

app/controllers/customer/passwords_controller.rb
# frozen_string_literal: true

class Customer::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customer/registrations_controller.rb
# frozen_string_literal: true

class Customer::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postcode, :address, :phone_number])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customer/sessions_controller.rb
# frozen_string_literal: true

class Customer::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/customer/unlocks_controller.rb
# frozen_string_literal: true

class Customer::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/customer/addresses_helper.rb
module Customer::AddressesHelper
end

app/helpers/customer/cart_items_helper.rb
module Customer::CartItemsHelper
end

app/helpers/customer/customers_helper.rb
module Customer::CustomersHelper
end

app/helpers/customer/homes_helper.rb
module Customer::HomesHelper
end

app/helpers/customer/items_helper.rb
module Customer::ItemsHelper
end

app/helpers/customer/orders_helper.rb
module Customer::OrdersHelper
end

app/views/customer/customers/edit.html.erb
<main>
  <div class="container">
    <div class="row">
      <div class="col-md-6 offset-md-1">
        <h2 class="my-5">会員情報編集</h2>
      </div>
    </div>
    <div class="row">
      <div class="mx-auto">
        <%= form_with model:@customer, local:true do |f| %>
          <table class="table table-borderless mb-5">
            <tbody>
             <tr>
                <th><%= f.label :名前 %></th>
                <td>
                  <div class="input-group">
                    <div class="d-flex input-group-prepend">
                      <span class="input-group-text">(姓)</span>
                    </div>
                    <%= f.text_field :first_name, autofocus: true, autocomplete: "first_name", placeholder: "令和",class: "form-control" %>
                  </div>
                </td>
                <td>
                  <div class="input-group">
                    <div class="d-flex input-group-prepend">
                      <span class="input-group-text">(名)</span>
                    </div>
                    <%= f.text_field :last_name, autocomplete: "last_name", placeholder: "道子",class: "form-control" %>
                  </div>
                </td>
              </tr>
              <tr>
                <th><%= f.label :フリガナ %></th>
                <td>
                  <div class="input-group">
                    <div class="d-flex input-group-prepend">
                      <span class="input-group-text">(セイ)</span>
                    </div>
                    <%= f.text_field :first_name_kana, autocomplete: "first_name_kana", placeholder: "レイワ",class: "form-control" %>
                  </div>
                </td>
                <td>
                  <div class="input-group">
                    <div class="d-flex input-group-prepend">
                      <span class="input-group-text">(メイ)</span>
                    </div>
                    <%= f.text_field :last_name_kana, autocomplete: "last_name_kana", placeholder: "ミチコ",class: "form-control" %>
                  </div>
                </td>
              </tr>
　  　        <tr>
                <th><%= f.label :郵便番号（ハイフンなし） %></th>
　　            <td><%= f.text_field :postcode, placeholder: "0000000", class:"form-control" %></td>
　          　  <td></td>
　          　</tr>
　          　<tr>
　  　          <th><%= f.label :住所 %></th>
　　            <td colspan="2"><%= f.text_field :address, autocomplete: "address", placeholder: "東京都渋谷区代々木神園町0-0",class: "form-control" %></td>
　　          </tr>
　          　<tr>
                <th><%= f.label :電話番号（ハイフンなし） %></th>
　　            <td><%= f.text_field :phone_number, autocomplete: "phone_number", placeholder: "000000000",class: "form-control" %></td>
　          　  <td></td>
　          　</tr>
　          　<tr>
　　            <th><%= f.label :メールアドレス %></th>
　　            <td><%= f.email_field :email, autocomplete: "email", placeholder: "sample@sample.com",class: "form-control" %></td>
　          　  <td></td>
　          　</tr>
            </tbody>
　      　</table>
　　      <div class="col text-center mb-5">
              <%= f.submit "変更を保存" ,class: "btn btn-success " %>
              <%= link_to "退会する" , unsubscribe_path(@customer), class: "btn btn-danger mt-auto" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</main>

app/views/customer/customers/show.html.erb
<main>
  <div class="container">
    <div class="mx-auto">
      <div class="row">
        <div class="col-md-6 offset-md-1">
          <h2 class="my-5">マイページ</h2>
        </div>
      </div>
      <div class="row">
        <div class="col-md-3 offset-md-1">
          <table class="table table-borderless mb-1">
            <tr>
              <th>登録情報</th>
              <td><%= link_to "編集する", edit_customer_path(@customer), class: "btn btn-sm btn-success" %></td>
            </tr>
          </table>
        </div>
      </div>
      <div class="row">
        <div class="col-md-8 mx-auto">
          <table class="table table-bordered mb-1">
            <tbody>
              <tr>
                <th class="table-warning">氏名</th>
                <td>
                  <%= @customer.first_name %>
                  <%= @customer.last_name %>
                </td>
              </tr>
              <tr>
                <th class="table-warning">フリガナ</th>
                <td>
                  <%= @customer.first_name_kana %>
                  <%= @customer.last_name_kana %>
                </td>
              </tr>
              <tr>
                <th class="table-warning">郵便番号</th>
                <td><%= @customer.postcode %></td>
              </tr>
              <tr>
                <th class="table-warning">住所</th>
                <td><%= @customer.address %></td>
              </tr>
              <tr>
                <th class="table-warning">電話番号</th>
                <td><%= @customer.phone_number %></td>
              </tr>
              <tr>
                <th class="table-warning">メールアドレス</th>
                <td><%= @customer.email %></td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
      <div class="row">
        <div class="col-md-3 offset-md-1">
          <table class="table table-borderless mb-5">
            <tr>
              <th>配送先</th>
              <td><%= link_to "一覧を見る", addresses_path, class: 'btn btn-sm btn-primary' %></td>
            </tr>
            <tr>
              <th>注文履歴</th>
              <td><%= link_to "一覧を見る", orders_path, class: 'btn btn-sm btn-primary' %></td>
            </tr>
          </table>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/customer/customers/unsubscribe.html.erb
<main>
  <div class="container">
    <div class="row">
      <div class="offset-1 mx-auto my-5">
        <h1 class="red-border px-3">本当に退会しますか？</h1>
      </div>
    </div>
    <div class="row my-5">
      <div class="offset-2 mx-auto">
        <p>退会すると、会員登録情報やこれまでの購入履歴が閲覧できなくなります。</p>
        <p style="text-align:center">退会する場合は、「退会する」をクリックしてください</p>
      </div>
    </div>
    <div class="row">
      <div class="offset-3 col-2 mb-5">
        <!--注文履歴一覧へ飛ぶ-->
        <%= link_to "退会しない" ,customer_path(current_customer), class: "btn btn-outline-danger" %>
      </div>
      <div class="offset-3 col-2 mb-5">
        <!-- 会員ステータスを無効に切り替えるoutアクションを呼ぶ-->
        <%= link_to "退会する" , out_path,method: :patch, class: "btn btn-danger" %>
      </div>
    </div>
  </div>
</main>