config/routes.rb
Rails.application.routes.draw do

   # 顧客側のdeviseルーティング設定
  devise_for :customers, controllers: {

    registrations: "customer/registrations",
    sessions: "customer/sessions"
  }


  root 'homes#top'

  # 管理者側のdeviseルーティング設定
  devise_for :admins, controllers: {
    sessions: "admin/sessions"
  }

  get 'about' => 'homes#about', as: 'about'


  #会員側のルーティング設定
  resources :addresses, except: [:show, :new]

  # resources の下にいると？うまく遷移しなかったので上にあげてみました。
  post 'orders/confirm' => 'orders#confirm', as: 'confirm'
  get 'orders/complete' => 'orders#complete', as: 'complete'
  resources :orders, except: [:edit, :update, :destroy]

  delete 'cart_items/alldestroy' => 'cart_items#all_destroy', as: 'all_destroy'
  resources :cart_items, except: [:show, :new, :edit]

  get 'items/search' => 'items#search', as: 'search'
  resources :items, only: [:index, :show]

  # 管理者側のルーティング設定
  namespace :admin do
    resources :order_details, only: :update
    resources :orders, only: [:index, :show, :update]
    resources :categories, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :items, except: :destroy
  end

  scope module: :customer do
    get 'customers/unsubscribe' => 'customers#unsubscribe', as: 'unsubscribe'
    patch 'customers/out' => 'customers#out', as: 'out'
    resources :customers, only: [:show, :edit, :update]
  end

end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    
    belongs_to :item
    belongs_to :customer
    
    validates :item_id,  presence: true
    validates :quantity,  presence: true
    
    
  
    def subtotal
     item.with_tax_price * quantity
    end
  
    
    
    
    
    
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  def index
    @items = current_customer.cart_items.all
    @total = 0
  end

  def create
    @cart = current_customer.cart_items.find_by(item_id: params[:cart_item][:item_id])
    @cart_item = current_customer.cart_items.new(cart_item_params)
    if @cart.present?
      @cart_item.quantity += @cart.quantity
      @cart.destroy
    end
    @cart_item.save
    redirect_to cart_items_path
  end

  # def create
  #   @cart = current_customer.cart_items.find_by(params[:cart_item][:item_id])
  #   if @cart.nil?
  #     @cart_item = current_customer.cart_items.new(cart_item_params)
  #     @cart_item.save
  #   else
  #     @cart.quantity +=  params[:cart_item][:quantity].to_i
  #     @cart.save
  #   end
  #   redirect_to cart_items_path
  # end

  def update
    @items =current_customer.cart_items
    if @items.update(cart_item_params)
    redirect_to cart_items_path
    else
      render :index
    end
  end

  def destroy
    @items =current_customer.cart_items.find(params[:id])
    @items.destroy
    redirect_to cart_items_path
  end

  def all_destroy
    @items =current_customer.cart_items
    @items.destroy_all
    redirect_to cart_items_path
  end


  private

  def cart_item_params
      params.require(:cart_item).permit(:item_id, :quantity)
  end




end

app/controllers/customer/cart_items_controller.rb
class Customer::CartItemsController < ApplicationController
  def index
  end

  def create
  end

  def update
  end

  def destroy
  end

  def all_destroy
  end
end

app/helpers/customer/cart_items_helper.rb
module Customer::CartItemsHelper
end

app/views/cart_items/index.html.erb
<main>
  <div class="container">
    <div class="row">
      <div class="col-md-8 offset-md-1 my-5">
        <h2>ショッピングカート</h2>
      </div>
      <div class="col-md-2 my-5">
        <div class="text-right">
          <%= link_to "カートを空にする", all_destroy_path, method: :delete, class:"btn btn-danger" %>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-10 offset-md-1 mb-5">
        <table class="table table-bordered mx-atuo">
          <thead class="table-warning">
            <th style="width: 35%">商品名</th>
            <th style="width: 15%">単価（税込）</th>
            <th style="width: 20%">数量</th>
            <th style="width: 15%">小計</th>
            <th style="width: 15%"></th>
          </thead>
          <tbody>
            <% @items.each do |cart_item| %>
            <tr>
              <td>
                <%= attachment_image_tag cart_item.item, :image, format: '.jpeg', size: "60x40" %>
                <%= cart_item.item.name %>
              </td>
              <td class="align-middle">
                <%= cart_item.item.with_tax_price.to_s(:delimited) %>
              </td>
              <td>
                <%= form_with model:cart_item, local: true do |f| %>
                  <div class="d-flex">
                  　<%= f.select :quantity, [1,2,3,4,5,6,7,8,9,10], {prompt: ""}, class: 'form-control' %>
                    <%= f.submit "更新", class: 'btn btn-success ml-2' %>
                  </div>
                <% end %>
              </td>
              <td class="align-middle">
                <%= cart_item.subtotal.to_s(:delimited) %>
              </td>
                <% (@total +=  cart_item.subtotal) %>
                <!--↑ここわけわからん　０にトータル代入していい感じにしてるっぽい-->
              <td>
                <%= link_to "削除する",cart_item_path(cart_item), method: :delete, class:"btn btn-danger" %>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
       </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-2 offset-md-2 mb-5">
        <%= link_to "買い物を続ける", items_path, class: "btn btn-primary", type:"button" %>
      </div>
      <div class="col-md-3 offset-md-3 mb-5">
        <table class="table table-bordered float-md-light">
          <tr>
            <th class="table-warning"  style="width: 50%">合計金額</th>
            <td style="width: 50%"><%= @total.to_s(:delimited) %></td>
          </tr>
        </table>
      </div>
    </div>
    <div class="row">
      <div class="mx-auto mb-5">
         <%= link_to "情報入力にすすむ", new_order_path(current_customer.id), class: "btn btn-success" %>
      </div>
    </div>
  </div>
</main>