config/routes.rb
Rails.application.routes.draw do

   # 顧客側のdeviseルーティング設定
  devise_for :customers, controllers: {

    registrations: "customer/registrations",
    sessions: "customer/sessions"
  }


  root 'homes#top'

  # 管理者側のdeviseルーティング設定
  devise_for :admins, controllers: {
    sessions: "admin/sessions"
  }

  get 'about' => 'homes#about', as: 'about'


  #会員側のルーティング設定
  resources :addresses, except: [:show, :new]

  # resources の下にいると？うまく遷移しなかったので上にあげてみました。
  post 'orders/confirm' => 'orders#confirm', as: 'confirm'
  get 'orders/complete' => 'orders#complete', as: 'complete'
  resources :orders, except: [:edit, :update, :destroy]

  delete 'cart_items/alldestroy' => 'cart_items#all_destroy', as: 'all_destroy'
  resources :cart_items, except: [:show, :new, :edit]

  get 'items/search' => 'items#search', as: 'search'
  resources :items, only: [:index, :show]

  # 管理者側のルーティング設定
  namespace :admin do
    resources :order_details, only: :update
    resources :orders, only: [:index, :show, :update]
    resources :categories, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :items, except: :destroy
  end

  scope module: :customer do
    get 'customers/unsubscribe' => 'customers#unsubscribe', as: 'unsubscribe'
    patch 'customers/out' => 'customers#out', as: 'out'
    resources :customers, only: [:show, :edit, :update]
  end

end

app/models/category.rb
class Category < ApplicationRecord

  has_many :items


end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @category = Category.new
    @categories = Category.all
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to admin_categories_path
    else
      @categories = Category.all
      render :index
    end
  end

  def edit
    @category =Category.find(params[:id])
  end

  def update
    @category =Category.find(params[:id])
    @category.update(category_params)
    redirect_to admin_categories_path
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end
  
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/views/admin/categories/edit.html.erb
<main>
  <div class="container">
    <div class="row">
      <div class="col-md-6 offset-md-1">
        <h2 class="my-5">ジャンル編集</h2>
        <%= form_with model: [:admin, @category], local:true, class: 'form-group row' do |f| %>
          <div class="col-auto">
            <label class="col-form-label">ジャンル名</label>
          </div>
          <div class="col-auto">
            <%= f.text_field :name, class: 'form-control' %>
          </div>
          <div class="col-auto">
            <%= f.submit '変更を保存', class: 'btn btn-success mb-3' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</main>

app/views/admin/categories/index.html.erb
<main>
  <div class="container">
    <div class="row">
      <div class="col-md-6 offset-md-1">
        <h2 class="my-5">ジャンル一覧・追加</h2>
      </div>
    </div>
    <div class="row">
      <div class="mx-auto">
        <%= form_with model: [:admin, @category], local:true, class: 'form-group row' do |f| %>
          <div class="col-auto">
            <label class="col-form-label">ジャンル名</label>
          </div>
          <div class="col-auto">
            <%= f.text_field :name, placeholder: 'ジャンル名', class: 'form-control'  %>
          </div>
          <div class="col-auto">
            <%= f.submit '新規登録', class: 'btn btn-success mb-3' %>
          </div>
        <% end %>
      </div>
    </div>
    <div class="row">
      <div class="mx-auto">
        <table class="table">
          <thead>
            <tr>
              <th>ジャンル</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% @categories.each do |category| %>
              <tr>
                <td><%= category.name %></td>
                <td><%= link_to '編集する', edit_admin_category_path(category.id), class: 'btn btn-sm btn-success' %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</main>